services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: next-app
    container_name: next-app
    command: sh -c "npm run dev"
    ports:
      - '3001:3000'
    env_file:
      - .env
    volumes:
      - ./src:/app
    restart: always
    tty: true
    stdin_open: true
  api:
    build:
      context: ../simple_todo_node
    container_name: api
    volumes:
      - ../simple_todo_node:/simple_todo
      - ../simple_todo_node/node_modules:/simple_todo/node_modules
    # command: node index.js
    ports:
      - 8000:1234
    env_file: ../simple_todo_node/.env.development
    tty: true
    stdin_open: true
  mysql:
    image: mysql:8.0.28
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple_todo
      TZ: "Asia/Tokyo"
    volumes:
      - ../simple_todo_node/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ../simple_todo_node/mysql:/var/lib/mysql

networks:
  default:
    name: develop.next-app-router
    external: true
